### ISSUE TITLE
Todo List markers in a preview window are stripped

### ISSUE THREAD

**Issue by CatChenal** [foambubble/foam#1013]
### Describe the bug

I am splitting the second issue in #1012.

The window that pops up on hovering over the `[[todo]]` tag contains the contents of `todo.md` (it also has a footer).  
Here is the entire file, which is correctly written for rendering ToDo list items in Markdown:
```
# Todo

You can create todos in Foam.

- [x] This is an example of a todo list item that's complete
- [ ] This one is not completed yet
- [ ] You can mark it completed by pressing `Option`+`C` (or `Alt`+`C`) when your cursor is on this line
  - [ ] You can also select multiple lines and mark them all at once!
```

### BUG:   
When rendered in the preview/pop-up window, the list is a common one, i.e. the brackets have been stripped.

### Steps to Reproduce the Bug or Issue

1. Open VS Code
2. Navigate to your Foam repo
3. Open `inbox.md` and `todo.md`
4. Verify that the list in `todo.md` is a Markdown ToDo list, e.g.:     
```Markdown
- [x] This is an example of a todo list item that's complete  
```
5. Switch to `inbox.md` & hover over the `[[todo]]` link
6. The text is rendered as:
# Todo

You can create todos in Foam.

-  This is an example of a todo list item that's complete
-  This one is not completed yet
-  You can mark it completed by pressing `Option`+`C` (or `Alt`+`C`) when your cursor is on this line
  -  You can also select multiple lines and mark them all at once!

### Expected behavior

It seems [/_layouts/foam.html#L18L43](https://github.com/foambubble/foam/blob/748df5e352d64d9d42c976da4e2cc5ae5caa8f36/docs/_layouts/foam.html#L18L43) is stripping Markdown's bracketed links... even when they are not.  
An exception should be made for ToDo lists, which use the same brackets.

### Operating System Version

Windows 10

### Visual Studio Code Version

Version: 1.68.0

### Additional context

Version: 1.68.0 (system setup)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:16.822Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by riccardoferretti** [comment]
I don't think the issue is related to `/_layouts/foam.html` as that one is not used by VS Code but only by github pages/jekyll.

I believe the issue is with VS Code `MarkdownString` class: https://vshaxe.github.io/vscode-extern/vscode/MarkdownString.html

This is where we create the tooltip, and you can see we use the `MarkdownString`: https://github.com/foambubble/foam/blob/748df5e352d64d9d42c976da4e2cc5ae5caa8f36/packages/foam-vscode/src/utils.ts#L181

I checked the content that goes in there is correct (`- [ ] xyz`) and yet it's removed in the preview.
